# Generated by Django 6.0.6 on 2026-06-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorshift",
            name="vagas_totais",
            field=models.IntegerField(default=10),
        ),
    ]
