# Generated by Django 6.0.6 on 2026-06-05 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_doctorshift_vagas_totais"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "medico"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.specialty",
            ),
        ),
    ]
