# Generated by Django 6.0.6 on 2026-07-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_intercurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="has_previous_record",
            field=models.BooleanField(default=False),
        ),
    ]
